### ISSUE TITLE
Error: m2u.maya.ui : Unable to load PySide

### ISSUE THREAD

**Issue by azoof-ahmed** [m2u/m2u#5]
I have already installed PySide by running command `pip install PySide`  but I dont have Qt installed since Pyside installs all required Qt libraries. So how do I fix this 😟 😿

**Comment by alfalfasprossen** [comment]
Are you using Maya 2017? It uses PySide2 internally. Installing PySide via pip will not help in that case. We will have to implement a compatibility layer in m2u (for example [Qt.py](https://github.com/mottosso/Qt.py)) to allow dealing with both, PySide (Qt4) and PySide2 (Qt5).

https://fredrikaverpil.github.io/2016/07/25/dealing-with-maya-2017-and-pyside2/

**Comment by leestuartx** [comment]
Here's the latest with adjustments made for Pyside2 
[m2u.zip](https://github.com/m2u/m2u/files/1237464/m2u.zip)

**Comment by azoof-ahmed** [comment]
Great, works perfectly with Maya 2017 (or rather Qt5). Thanks
